---
# Tenant A Specific Information - VRFs / VLANs
Tenant_A:
  - name: "Tenant_A"
    mac_vrf_vni_base: 10000
    vrfs:
      - name: Tenant_A_OP_Zone
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          - id: 110
            name: Tenant_A_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 111
            vni_override: 50111
            name: Tenant_A_OP_Zone_2
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.11.1/24
          - id: 112
            vni_override: 50112
            name: Tenant_A_OP_Zone_3
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.12.254/24
      - name: Tenant_A_WEB_Zone
        vrf_vni: 11
        svis:
          - id: 120
            name: Tenant_A_WEB_Zone_1
            tags: [web, erp1]
            enabled: true
          - id: 121
            name: Tenant_A_WEBZone_2
            tags: [web]
            enabled: true
            ip_address_virtual: 10.1.21.1/24
      - name: Tenant_A_APP_Zone
        vrf_vni: 12
        svis:
          - id: 130
            name: Tenant_A_APP_Zone_1
            tags: [app, erp1]
            enabled: true
          - id: 131
            name: Tenant_A_APP_Zone_2
            tags: [app]
            enabled: true
            ip_address_virtual: 10.1.31.254/24
      - name: Tenant_A_DB_Zone
        vrf_vni: 13
        svis:
          - id: 140
            name: Tenant_A_DB_BZone_1
            tags: [db, erp1]
            enabled: true
            ip_address_virtual: 10.1.40.1/24
          - id: 141
            name: Tenant_A_DB_Zone_2
            tags: [db]
            enabled: true
            ip_address_virtual: 10.1.41.1/24
      - name: Tenant_A_WAN_Zone
        vrf_vni: 14
        svis:
          - id: 150
            name: Tenant_A_WAN_Zone_1
            tags: [wan]
            enabled: true
            ip_address_virtual: 10.1.40.1/24
    l2vlans:
      - id: 160
        vni_override: 55160
        name: Tenant_A_VMOTION
        tags: [vmotion]
      - id: 161
        name: Tenant_A_NFS
        tags: [nfs]
