---
# L3LS Fabric Values - update these values with caution,
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_FABRIC

# Enable vlan aware bundles
evpn_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  mlag_ipv4_underlay_peer:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Spine Switches
spine:
  defaults:
    platform: vEOS-LAB
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    structured_config:
      router_bgp:
        bgp:
          default:
            ipv4_unicast: false
        distance:
          external_routes: 20
          internal_routes: 200
          local_routes: 200
        graceful_restart:
          enabled: true
          restart_time: 300
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 10.255.0.11/24
    DC1-SPINE2:
      id: 2
      mgmt_ip: 10.255.0.12/24

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2']
    uplink_switches: ['DC1-SPINE1', 'DC1-SPINE2']
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    structured_config:
      router_bgp:
        bgp:
          default:
            ipv4_unicast: false
        distance:
          external_routes: 20
          internal_routes: 200
          local_routes: 200
        graceful_restart:
          enabled: true
          restart_time: 300
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 10.255.0.13/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.255.0.14/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    DC1_LEAF2:
      bgp_as: 65102
      nodes:
        DC1-LEAF2A:
          id: 3
          mgmt_ip: 10.255.0.15/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        DC1-LEAF2B:
          id: 4
          mgmt_ip: 10.255.0.16/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]


l2leaf:
  defaults:
    platform: vEOS-LAB
    uplink_switches: ['DC1-LEAF1A', 'DC1-LEAF1B']
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    mlag: false
  node_groups:
    DC1_L2LEAF1:
      uplink_switches: [ DC1-LEAF1A, DC1-LEAF1B ]
      filter:
        tenants: [ Tenant_A ]
        tags:
          - app
          - opzone
          - web
      nodes:
        DC1-L2LEAF1A:
          id: 5
          mgmt_ip: 10.255.0.17/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
    DC1_L2LEAF2:
      uplink_switches: [ DC1-LEAF2A, DC1-LEAF2B ]
      filter:
        tenants: [ Tenant_A ]
        tags:
          - app
          - opzone
          - web
      nodes:
        DC1-L2LEAF2A:
          id: 7
          mgmt_ip: 10.255.0.18/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]

p2p_uplinks_mtu: 9000

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.

# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES


#### Override for vEOS Lab Caveats ####
# Refer to design guide

platform_settings:
  - platforms:
      - default
  - platforms:
      - vEOS-LAB
    reload_delay:
      # In seconds.
      mlag: 300
      # In seconds.
      non_mlag: 330
    feature_support:
      queue_monitor_length_notify: false
      interface_storm_control: false
      poe: false

      # Support for configuration of per interface MTU for p2p links, MLAG SVIs and Network Services.
      # Effectively this means that all settings regarding interface MTU will be ignored if this is false.
      # Platforms without support for per interface MTU can use a single default interface MTU setting. Set this via "default_interface_mtu"
      per_interface_mtu: false

      # Disables FIB updates and route advertisement when the BGP instance is initiated until the BGP convergence state is reached.
      # Can be overridden by setting "bgp_update_wait_install" host/group_vars.
      bgp_update_wait_install: false

      # Do not advertise reachability to a prefix until that prefix has been installed in hardware.
      # This will eliminate any temporary black holes due to a BGP speaker advertising reachability to a prefix that may not yet be installed into the forwarding plane.
      # Can be overridden by setting "bgp_update_wait_for_convergence" host/group_vars.
      bgp_update_wait_for_convergence: false
